from pathlib import Path

client_code = (
    "import os\n"
    "from typing import Any, Dict, List, Optional\n\n"
    "from pymilvus import Collection, connections, utility\n\n"
    "from app.vector_db.schemas import rai_schema, customer_schema\n\n"
    "DEFAULT_RAI_COLLECTION = os.getenv(\"MILVUS_RAI_COLLECTION\", \"rai_docs_test\")\n"
    "DEFAULT_CUSTOMER_COLLECTION = os.getenv(\"MILVUS_CUSTOMER_COLLECTION\", \"customer_context_test\")\n\n\n"
    "class MilvusVectorDB:\n"
    "    def __init__(self, uri: str, token: str, alias: str = \"default\"):\n"
    "        self.uri = uri\n"
    "        self.token = token\n"
    "        self.alias = alias\n\n"
    "    def connect(self) -> None:\n"
    "        connections.connect(alias=self.alias, uri=self.uri, token=self.token)\n\n"
    "    def ensure_collections(self, rai_name: str = DEFAULT_RAI_COLLECTION, customer_name: str = DEFAULT_CUSTOMER_COLLECTION) -> None:\n"
    "        if not utility.has_collection(rai_name, using=self.alias):\n"
    "            Collection(name=rai_name, schema=rai_schema(), using=self.alias)\n"
    "        if not utility.has_collection(customer_name, using=self.alias):\n"
    "            Collection(name=customer_name, schema=customer_schema(), using=self.alias)\n"
    "        self._ensure_index_and_load(rai_name)\n"
    "        self._ensure_index_and_load(customer_name)\n\n"
    "    def _ensure_index_and_load(self, collection_name: str) -> None:\n"
    "        col = Collection(collection_name, using=self.alias)\n"
    "        if not col.indexes:\n"
    "            col.create_index(field_name=\"embedding\", index_params={\"index_type\": \"AUTOINDEX\", \"metric_type\": \"COSINE\"})\n"
    "        col.load()\n\n"
    "    def upsert_rai(self, items: List[Dict[str, Any]], collection_name: str = DEFAULT_RAI_COLLECTION) -> None:\n"
    "        col = Collection(collection_name, using=self.alias)\n"
    "        data = [[i[\"id\"] for i in items], [i[\"text\"] for i in items], [i.get(\"source\", \"\") for i in items], [i.get(\"doc_id\", \"\") for i in items], [i[\"embedding\"] for i in items]]\n"
    "        col.insert(data)\n"
    "        col.flush()\n\n"
    "    def upsert_customer(self, items: List[Dict[str, Any]], collection_name: str = DEFAULT_CUSTOMER_COLLECTION) -> None:\n"
    "        col = Collection(collection_name, using=self.alias)\n"
    "        data = [[i[\"id\"] for i in items], [i[\"customer_id\"] for i in items], [i[\"text\"] for i in items], [i[\"embedding\"] for i in items]]\n"
    "        col.insert(data)\n"
    "        col.flush()\n\n"
    "    def search(self, query_embedding: List[float], collection_name: str, top_k: int = 3, filter_expr: Optional[str] = None) -> List[Dict[str, Any]]:\n"
    "        col = Collection(collection_name, using=self.alias)\n"
    "        col.load()\n"
    "        results = col.search(data=[query_embedding], anns_field=\"embedding\", param={\"metric_type\": \"COSINE\"}, limit=top_k, expr=filter_expr, output_fields=[\"id\", \"text\", \"source\", \"doc_id\", \"customer_id\"])\n"
    "        return [{\"id\": h.entity.get(\"id\"), \"score\": float(h.score), \"text\": h.entity.get(\"text\"), \"source\": h.entity.get(\"source\"), \"doc_id\": h.entity.get(\"doc_id\"), \"customer_id\": h.entity.get(\"customer_id\")} for h in results[0]]\n"
)

Path("app/vector_db/milvus_client.py").write_text(client_code, encoding="utf-8")
print("milvus_client.py overwritten cleanly")
